<a href="https://colab.research.google.com/github/Tomoyuki0223/machine_learning_question/blob/main/kadai12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.animation
from IPython.display import HTML

#（1）Sの計算

In [2]:
X = np.array([[-7, -2], [-3, -3], [4, 1], [6, 4]])

In [3]:
S = X.T @ X
S

array([[110,  51],
       [ 51,  30]])

#（2）固有値問題の解

In [4]:
S_eig = np.linalg.eig(S)
λ = S_eig[0]
u = S_eig[1]

In [5]:
λ #固有値

array([134.81512169,   5.18487831])

In [6]:
u #固有ベクトル（正規化済）

array([[ 0.89920519, -0.43752718],
       [ 0.43752718,  0.89920519]])

# (3)(4) 第1主成分と第2主成分

### 第一主成分

In [7]:
u_1 = u[:,0]
u_1 #第一主成分

array([0.89920519, 0.43752718])

In [9]:
a_1 = X @ u_1
a_1 #第一主成分得点

array([-7.16949066, -4.0101971 ,  4.03434793,  7.14533984])

In [13]:
J_1 = sum(a_1**2)/len(a_1)
J_1 #分散

33.7037804230988

### 第二主成分

In [14]:
u_2 = u[:,1]
u_2 #第二主成分

array([-0.43752718,  0.89920519])

In [15]:
a_2 = X @ u_2
a_2 #第二主成分得点

array([ 1.26427988, -1.38503402, -0.85090353,  0.97165767])

In [16]:
J_2 = sum(a_2**2)/len(a_2)
J_2 #分散

1.2962195769011975